# Generated by Django 6.0.5 on 2026-05-27 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('src_type', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('err', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NormRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('raw_val', models.DecimalField(decimal_places=6, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('norm_val', models.DecimalField(decimal_places=6, max_digits=18)),
                ('norm_unit', models.CharField(default='kgCO2e', max_length=10)),
                ('em_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('act_date', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.datasource')),
                ('raw', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.rawrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant'),
        ),
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('severity', models.CharField(default='WARNING', max_length=10)),
                ('msg', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ingest.normrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=20)),
                ('old_val', models.JSONField(blank=True, null=True)),
                ('new_val', models.JSONField(blank=True, null=True)),
                ('tstamp', models.DateTimeField(auto_now_add=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ingest.normrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant')),
            ],
        ),
    ]
